#!/usr/bin/sh

echo 'Pre-commit hook'

echo '[1/2] Building JavaScript…'

yarn build
git add src/main/webapp/papes.js

echo '[2/2] Copying src/main/webapp/ -> docs/'

rm -rf docs/
cp -R src/main/webapp/ docs/
git add docs/*