#!/usr/bin/sh

echo 'Pre-commit hook'


if git diff --cached --name-only | grep --quiet "src/main/webapp/scripts"
then
    echo '* Building JavaScript'
    yarn build
    git add src/main/webapp/papes.js
else
    echo '* JavaScript has not changed'
fi

if git diff --cached --name-only | grep --quiet "src/main/webapp"
then
    echo '* Copying src/main/webapp/ -> docs/'
    rm -rf docs/
    cp -R src/main/webapp/ docs/
    git add docs/*
else
    echo '* webapp/ has not changed'
fi